export const types = {
  FETCHING_POSTS: "FETCHING_POSTS",
  SUCCESS_FETCHING_POSTS: "SUCCESS_FETCHING_POSTS",
  FAILER_FETCHING_POSTS: "FAILER_FETCHING_POSTS",

  CHANGE_POST_INPUT: "CHANGE_POST_INPUT",
  ADDING_POST: "ADDING_POST",
  SUCCESS_ADDING_POST: "SUCCESS_ADDING_POST",
  FAILER_ADDING_POST: "FAILER_ADDING_POST",
};
